[package]
name = "cairo-proof-parser"
version = "0.2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cairo-proof-parser"
path = "src/bin/main.rs"  # Adjust the path to where your binary's main file is

[dependencies]
anyhow = "1.0.81"
itertools = "0.12.1"
num-bigint = { version = "0.4.4", features = ["serde"] }
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
