[package]
name = "cairo-proof-parser"
version = "0.1.2"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
num-bigint = "0.4.4"
regex = "1.10.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.113"
cairo-platinum-prover = { git = "https://github.com/lambdaclass/lambdaworks.git", version = "0.5.0", features = [
    "instruments",
    "parallel",
] }
clap = { version = "4.5.0", features = ["derive"] }
lambdaworks-math = { git = "https://github.com/lambdaclass/lambdaworks.git", version = "0.5.0" }
stark-platinum-prover = { git = "https://github.com/lambdaclass/lambdaworks.git", version = "0.5.0" }
